name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  macos_build:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/test_configure_git_user
  ubuntu_build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/test_configure_git_user

