name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:

  test_with_defaults:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/test_configure_git_user
      with:
        expected_user_name: ${{ github.actor }}
        expected_user_email: ${{ github.actor }}@users.noreply.github.com

  # test_without_path:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ./.github/actions/test_configure_git_user

#   test_without_path:
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#     - uses: ./.github/actions/test_configure_git_user
