name: CI for PR Merge

on:
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:

  test_with_defaults:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/test_configure_git_user
      with:
        expected_user_name: ${{ github.actor }}
        expected_user_email: ${{ github.actor }}@users.noreply.github.com

  test_with_path:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Create a git repo
      id: create_git_repo
      shell: bash
      run: |
        repo_path="${HOME}"/test_git_repo
        mkdir -p "${repo_path}"
        cd "${repo_path}"
        git init -b main
        echo "::set-output name=repo_path::${repo_path}"
    - uses: ./.github/actions/test_configure_git_user
      with:
        repo_path: ${{ steps.create_git_repo.outputs.repo_path }}
        expected_user_name: ${{ github.actor }}
        expected_user_email: ${{ github.actor }}@users.noreply.github.com

  all_test_ci_tests:
    runs-on: ubuntu-20.04
    needs: [test_with_defaults, test_with_path]
    steps:
      - name: Join all results
        shell: bash
        run: |
          echo "All is well!"

  # test_without_path:
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - uses: ./.github/actions/test_configure_git_user

#   test_without_path:
#     runs-on: ubuntu-20.04
#     steps:
#     - uses: actions/checkout@v2
#     - uses: ./.github/actions/test_configure_git_user
